### ISSUE TITLE
pkg_dict in vars/main.yml.sample doesn't result in any pkglists

### ISSUE THREAD

**Issue by norrland** [vbotka/ansible-freebsd-poudriere#1]
https://github.com/vbotka/ansible-freebsd-poudriere/blob/341b75a29c583b7d2635ec854a4291d885a60660/tasks/pkglist.yml#L14

The task that is using `{{ item.pkglist }}` in pkglist.yml could be updated to `{{ item.name }}`, unless you'd rather update the example in vars/main.yml.sample :).

Tested with ansible 2.10.5

**Comment by vbotka** [comment]
Thank you! I've fixed the examples in vars/main.yml.sample

For the record. Use defaults of the role vbotka.freebsd_postinstall from files [pkgdict_*.yml](https://github.com/vbotka/ansible-freebsd-postinstall/tree/master/defaults/main).
